config/routes.rb
Rails.application.routes.draw do
  # resources :recipes
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :foods

  root to: "recipes#public_recipes"
  resources :recipes, only: [:index, :show, :new, :create, :destroy, :update] do
    resources :recipe_foods
  end
  get 'recipe/public_recipes', to: "recipes#public_recipes", as: "public_recipes"
  get 'recipe/show/shopping_list/:id', to: "recipes#generate_shopping_list", as: "shopping_list"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, RecipeFood
    return unless user.present?

    # Food related permissions for user
    can :create, Food # any user can create a food
    can :destroy, Food do |food| # only the user who created the food can destroy it
      food.user_id == user.id
    end

    # Recipe related permissions for user
    can :create, Recipe # any user can create a recipe
    can :manage, Recipe do |recipe| # only the user who created the recipe can read it
      recipe.user_id == user.id
    end

    # RecipeFood related permissions for user
    can :create, RecipeFood # any user can create a recipe_food
    can :manage, RecipeFood do |recipe_food| # only the user who created the recipe_food can read it
      recipe_food.user_id == user.id
    end

    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
  validates :qty, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :foods
  has_many :recipes

  validates :name, presence: true
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /foods or /foods.json
  def index
    @foods = Food.all.order('created_at ASC')
    @food = Food.new
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = current_user.foods.build
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.build(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :qty)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def index
    @recipe_foods = RecipeFood.all
  end

  def new
    @recipe_food = RecipeFood.new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.where(user_id: current_user.id)
  end

  def create
    @recipe_food = RecipeFood.new(params.require(:recipe_food).permit(:qty, :food_id))
    @recipe = Recipe.find(params[:recipe_id])

    @recipe_food.recipe_id = @recipe.id

    if @recipe_food.save
      flash[:success] = 'Ingredient is added successfully'
      redirect_to recipe_path(@recipe)
    else
      flash.now[:error] = 'Ingredient is not added!!!'
      redirect_to new_recipe_recipe_food_path(@recipe)
    end
  end

  def destroy
    RecipeFood.find(params[:id]).destroy
    redirect_to recipe_path(params[:recipe_id])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[public_recipes]

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes.order('created_at ASC')
    @recipe = Recipe.new
  end

  def public_recipes
    @public_recipes = Recipe.includes(:user).where(public: true)
  end

  def generate_shopping_list
    @recipe_foods = RecipeFood.includes(:food).select { |item| item.food.user_id == current_user.id }
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food)
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipes_path, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Qty:</strong>
    <%= food.qty %>
  </p>

</div>

app/views/foods/_form.html.erb
<%= simple_form_for(@food) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :name,
          label: "Name",
          required: true,
          autofocus: true,
          placeholder: "food name",
          input_html: { class: "input", autocomplete: "name" },
          wrapper: false,
          label_html: { class: "label" } %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :measurement_unit,
          label: "Measurement Unit",
          required: true,
          placeholder: "measurement unit",
          input_html: { class: "input", autocomplete: "measurement_unit" },
          wrapper: false,
          label_html: { class: "label" } %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :price,
          label: "Price",
          required: true,
          placeholder: "price",
          input_html: { class: "input", autocomplete: "price" },
          wrapper: false,
          label_html: { class: "label" } %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :qty,
          label: "Quantity",
          required: true,
          placeholder: "quantity",
          input_html: { class: "input", autocomplete: "quantity" },
          wrapper: false,
          label_html: { class: "label" } %>
    </div>
  </div>
  <div class="buttons">
    <%= f.button :submit, "Add Food", class:"button is-save is-rounded is-normal" %>
    <%= link_to "Back to foods", foods_path, class: "button is-link is-light is-rounded is-normal" %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<section class="section">
  <div class="container">
    <div class="field is-grouped is-justify-content-right">
      <p class="control">
          <%= link_to new_food_path do %>
              <button 
                class="button js-modal-trigger is-save is-outlined is-rounded is-align-content-end" 
                data-target="modal-js-example">
                New Food
              </button>
          <% end %>  
      </p>
    </div>
    <div class="table-container">
      <table class="table is-bordered is-striped is-hoverable is-fullwidth">
        <thead class="thead">
          <tr>
            <th>Food</th>
            <th>Measurement Unit</th>
            <th>Unit Price</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do | food | %>
            <tr>
              <td><%= food.name %></td>
              <td><%= food.measurement_unit %></td>
              <td>$<%= food.price %></td>
              <td>
                <% if can? :destroy, food %>
                  <%= link_to food, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this food?' }, class: "level-item" do %>
                    <button class="button is-danger is-outlined is-rounded is-responsive">
                      <span><ion-icon name="trash"></ion-icon></span>
                    </button>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</section>

app/views/foods/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <h2 class="title is-2">New Food</h2>
        <%= render "form", food: @food %>
      </div>
    </div>
  </div>
</section>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipestash</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <!--#######################Flash Messages###########################-->
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
      <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

  <!--#######################Navbar Below###########################-->
    <%= render partial: "/partials/navbar" %>

    <%= yield %>

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar is-info">
    <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
            <h1 class="title is-5">RecipeStash</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
            <div class="field is-grouped">
                <% if user_signed_in? %>
                    <p class="control">
                        <%= link_to 'Foods', foods_path, class: "button is-info" %>
                    </p>
                    <p class="control">
                        <%= link_to 'Recipes', recipes_path, class: "button is-info" %>
                    </p>
                    <p class="control">
                        <%= link_to 'Public Recipes', public_recipes_path, class: "button is-info" %>
                    </p>
                    <p class="control">
                        <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
                    </p>
                    <p>
                        <!--%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %-->
                        <%= link_to "Logout", destroy_user_session_path, data: { "turbo-method": :delete }, class: "button is-info" %>
                        <!--%= button_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %-->
                    </p>
                <% else %>
                    <p class="control">
                        <%= link_to 'Public Recipes', public_recipes_path, class: "button is-info" %>
                    </p>
                    <p class="control">
                        <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
                    </p>
                    <p class="control">
                        <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
                    </p>
                <% end %> 
            </div>
        </div>
    </div>
</nav>

app/views/recipe_foods/new.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-8">
                <h2 class="title is-2">New Ingredient</h2>
                <%= simple_form_for([@recipe, @recipe_food])  do |f| %>
                   <%= f.error_notification %>
                   <span><%=f.label "Food", class: "label", required: true %></span>
                    <div class="field select is-link is-fullwidth">
                        <div class="control">
                            <%= f.select :food_id, @foods.map { |food| [food.name, food.id] }, 
                                label: "Food",
                                input_html: { class: "input" },
                                required: true,
                                wrapper: false,
                                label_html: { class: "label" } %>
                        </div>
                    </div>
                    <div class="field">
                        <div class="control">
                            <%= f.input :qty,
                                label: "Quantity",
                                required: true,
                                input_html: { class: "input", autocomplete: "qty" },
                                wrapper: false,
                                label_html: { class: "label" } %>
                        </div>
                    </div>
                    <div class="buttons">
                        <%= f.button :submit, "Add Ingredient", class:"button is-save is-rounded is-normal" %>
                        <%= link_to "Back to Recipe", :back, class: "button is-link is-light is-rounded is-normal" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/recipes/_form.html.erb
<%= simple_form_for(@recipe) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="field">
    <div class="control">
      <%= f.input :name,
          label: "Name",
          required: true,
          autofocus: true,
          placeholder: "food name",
          input_html: { class: "input", autocomplete: "name" },
          wrapper: false,
          label_html: { class: "label" } %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :preparation_time,
          label: "Preparation Time",
          required: true,
          placeholder: "preparation time",
          input_html: { class: "input", autocomplete: "preparation_time" },
          wrapper: false,
          label_html: { class: "label" } %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :cooking_time,
          label: "Cooking Time",
          required: true,
          placeholder: "cooking time",
          input_html: { class: "input", autocomplete: "cooking_time" },
          wrapper: false,
          label_html: { class: "label" } %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :description,
          label: "Description",
          required: true,
          placeholder: "description",
          input_html: { class: "textarea", autocomplete: "description" },
          wrapper: false,
          label_html: { class: "label" } %>
    </div>
  </div>
  <div class="field">
    <div class="control">
      <%= f.input :public, as: :boolean,
          checked_value: 'true',
          unchecked_value: 'false',
          label: "Is Public?",
          required: true,
          placeholder: "public",
          input_html: { class: "checkbox" },
          wrapper: false,
          label_html: { class: "label" } %>
    </div>
  </div>

  <div class="buttons">
    <%= f.button :submit, "Add Recipe", class:"button is-save is-rounded is-normal" %>
    <%= link_to "Back to recipes", recipes_path, class: "button is-link is-light is-rounded is-normal" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <h2 class="title is-2"><%= recipe.name %></h2>
  </p>
  <div class="box">
    <article class="media">
      <div class="media-content">
        <div class="content">
          <p>
            <strong>Preparation time:</strong>
            <%= recipe.preparation_time %>
          </p>
          <p>
            <strong>Cooking time:</strong>
            <%= recipe.cooking_time %>
          </p>
          <p><strong>Steps go here...</strong></p>
        </div>
        <br />
        <nav class="level">
          <% if can? :manage, recipe %>
            <div class="level-left is-mobile">
                <%= link_to shopping_list_path(current_user.id), method: :get, class: "level-item" do %>
                  <button class="button is-save is-outlined is-rounded is-responsive">Generate shopping list</button>
                <% end %>
            </div>
            <div class="level-right is-mobile">
                <%= link_to new_recipe_recipe_food_path(recipe.id), class: "level-item" do %>
                  <button class="button is-save is-outlined is-rounded is-responsive">Add ingredient</button>
                <% end %>
            </div>
          <% end %>
        </nav>
      </div>
      <div class="media-right">
        <figure class="image is-64x64">
          <% if recipe.public %>
            <span>Public <img src=<%= image_path("toggle-on.svg") %> /></span>
          <% else %>
            <span>Public <img src=<%= image_path("toggle-off.svg") %> /></span>
          <% end %>
        </figure>
      </div>
    </article>
  </div>
  <hr />
  <div class="table-container">
    <table class="table is-bordered is-striped is-hoverable is-fullwidth">
      <thead class="thead">
        <tr>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% recipe.recipe_foods.includes([:food]).each do | recipe_food | %>
          <tr>
            <td><%= recipe_food.food.name %></td>
            <td><%= recipe_food.qty %> <%= recipe_food.food.measurement_unit %></td>
            <td>$<%= recipe_food.qty*recipe_food.food.price%></td>
            <td>
              <% if can? :manage, @recipe %>
                <%= button_to "Remove", recipe_recipe_food_path(@recipe.id, recipe_food.id) , 
                    method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this recipe-food?' }, 
                    class: "button is-danger is-outlined is-rounded is-small is-responsive" %>
              <% else %>
                <span>No action is allowed for this recipe</span>
              <% end %>          
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/generate_shopping_list.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-half">
                <div class="is-flex is-justify-content-center">
                    <p><h2 class="title is-2">Shopping List</h2></p>
                </div>
                <div class="box">
                    <article class="media">
                        <div class="media-content">
                            <div class="content">
                                <% sum = 0%>
                                <% count = 0%>
                                <% @recipe_foods.each do |item| %>
                                    <% sum += item.qty * item.food.price %>
                                    <% count += 1 %>
                                <% end %>
                                <p class="is-flex is-justify-content-space-between">
                                    <strong>Amount of food items to buy: <%= count %></strong>
                                    <strong>Total value of food needed: $<%= sum %></strong>
                                </p>
                            </div>
                            <br />
                        </div>
                    </article>
                </div>
                <hr />
                <div class="table-container">
                    <table class="table is-bordered is-striped is-hoverable is-fullwidth">
                        <thead class="thead">
                            <tr>
                                <th>Food</th>
                                <th>Quantity</th>
                                <th>Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @recipe_foods.each do | recipe_food | %>
                                <tr>
                                <td><%= recipe_food.food.name %></td>
                                <td><%= recipe_food.qty %> <%= recipe_food.food.measurement_unit %></td>
                                <td>$<%= recipe_food.qty*recipe_food.food.price%></td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/recipes/index.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-half">
                <div class="field is-grouped is-justify-content-right">
                    <p class="control">
                        <%= link_to new_recipe_path do %>
                            <button 
                            class="button js-modal-trigger is-save is-outlined is-rounded is-align-content-end" 
                            data-target="modal-js-example">
                            New Recipe
                            </button>
                        <% end %>  
                    </p>
                </div>
                <% @recipes.each do | recipe | %>
                    <% if can? :manage, recipe %>
                        <div class="box">
                            <article class="media">
                                <div class="media-left">
                                    <figure class="image is-64x64">
                                        <img src="https://via.placeholder.com/64.png">
                                    </figure>
                                </div>
                                <div class="media-content">
                                    <div class="content">
                                        <strong><%= recipe.name %></strong><br />
                                        <p><%= recipe.description %></p>
                                    </div>
                                    <nav class="level">
                                        <div class="level-left is-mobile">
                                            <%= link_to recipe, class: "level-item" do %>
                                                <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                                            <% end %>
                                            <%= link_to recipe, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you wnat to delete this recipe?' }, class: "level-item" do %>
                                                <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                                            <% end %>
                                        </div>
                                    </nav>
                                </div>
                            </article>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/recipes/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <h2 class="title is-2">New Recipe</h2>
        <%= render "form", recipe: @recipe %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/public_recipes.html.erb
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-half">
                <% if user_signed_in? %>
                    <div class="field is-grouped is-justify-content-right">
                        <p class="control">
                            <%= link_to new_recipe_path do %>
                                <button 
                                class="button js-modal-trigger is-save is-outlined is-rounded is-align-content-end" 
                                data-target="modal-js-example">
                                New Recipe
                                </button>
                            <% end %>  
                        </p>
                    </div>
                <% end %> 

                <% @public_recipes.each do | recipe | %>
                    <div class="box">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-64x64">
                                    <img src="https://via.placeholder.com/64.png">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <strong><%= recipe.name %></strong><br />
                                    <p><%= recipe.description %></p>
                                    <small>By: @<%= recipe.user.username %></small><br />
                                </div>
                                <% if can? :manage, recipe %>
                                <nav class="level">
                                    <div class="level-left is-mobile">
                                        <%= link_to recipe, class: "level-item" do %>
                                            <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                                        <% end %>
                                        <%= link_to recipe, method: :delete, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you wnat to delete this recipe?' }, class: "level-item" do %>
                                            <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                                        <% end %>
                                    </div>
                                </nav>
                                <% end %>  
                            </div>
                        </article>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/recipes/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <%= render @recipe %>
      </div>
    </div>
  </div>
</section>